# -*- ispell-local-dictionary: "en_US" -*-
#+TITLE: Convert org-mode files to docx using Pandoc
#+LANGUAGE: en
#+PROPERTY: header-args :tangle no :exports code :mkdirp yes

I use Emacs org-mode to write documentation and to do project planning and
estimation. When I need to share a document with colleagues or clients who do
not use Emacs, I use [[https://pandoc.org/][Pandoc]] to convert my org-mode documents to docx.

* Generate a reference document

If you want to customize the style of the docx file generated by Pandoc, you
must first generate a reference document.

Pandoc can generate this reference template using the following command:

#+begin_src sh
pandoc -o custom-reference.docx --print-default-data-file reference.docx
#+end_src

Once generated, open =custom-reference.docx= in Microsoft Word and modify the
styles directly (headings, fonts, spacing, etc.).


* Convert org-mode to docx

You can convert an org-mode document to docx using the following command:

#+begin_src sh
pandoc -o my-document.docx my-document.org
#+end_src

To apply the custom styles defined in =custom-reference.docx=, use the
=--reference-doc= option. In my case, I also ask Pandoc to generate a table of
contents using =--toc=.

By default, the table of contents title is in English. Since my documents are
in French, I override it using =-M toc-title=:

#+begin_src sh
pandoc \
  --toc \
  -M toc-title="Table des matières" \
  --reference-doc custom-reference.docx \
  -o test.docx \
  test.org
#+end_src

If you want to make =custom-reference.docx= the default reference for all your
document, you can rename it to =reference.docx= and copy the file in pandoc user
data directory. On Windows the default user data directory is =%APPDATA%\pandoc=.
Once done, you can omit =--reference-doc= in the command line.

* Insert metadata in your docx document

To insert other metadata in the docx, you can use =--metadata-file= or =-M KEY[=VAL]=.

* Create an elisp function to call it from emacs

#+begin_src elisp :tangle "~/.emacs.d/elisp/my-org-to-docx.el"
  ;;; my-org-to-docx.el --- -*- lexical-binding: t; -*-
  ;;; Commentary:
  ;;  Small utilities to export org-mode to docx using pandoc
  ;;

  ;;; Code:

  (defun my/org-export-to-docx ()
    "Export the current org buffer to docx using pandoc."
    (interactive)
    (unless (derived-mode-p 'org-mode)
      (user-error "Not an Org buffer"))
    (unless buffer-file-name
      (user-error "Buffer is not visiting a file"))
    (save-buffer)
    (let* ((input buffer-file-name)
           (default-directory (file-name-directory input))
           (output (concat (file-name-sans-extension
                            (file-name-nondirectory input))
                           ".docx")))
      (if (zerop (call-process "pandoc" nil "*org-to-docx*" t
                               "--toc" "-M toc-title=\"Table des matières\"" input "-o" output))
          (message "Exported to %s" (expand-file-name output))
        (error "Pandoc export failed. See *org-to-docx* buffer"))))

  (provide 'my-org-to-docx)
  ;;; my-org-to-docx.el ends here
#+end_src
