# -*- ispell-local-dictionary: "en_US" -*-
#+TITLE:README
#+AUTHOR: L. Gualdi
#+LANGUAGE: en

* Introduction

A complete rewrite of my personal Emacs configuration, using literate
programming and org-mode. This file is inspired by configuration files of [[https://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua]],
[[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][Mathieu Marques]], [[https://jamiecollinson.com/blog/my-emacs-config/][Jamie Collinson]], [[https://github.com/protesilaos][Protesilaos Stavrou]], [[https://howardabrams.com/hamacs][Howard Abrams]], [[https://github.com/rougier/dotemacs/blob/master/dotemacs.org][Nicolas
Rougier]] and [[https://github.com/jamescherti/minimal-emacs.d][minimal-emacs.d]].

I'm running Emacs on Macosx and on Windows. I tried to make this
configuration compatible with both environment.

* How to use

Open [[file:./dotemacs.org][dotemacs.org]] with Emacs and tangle code using 'C-c C-v t' to initialize
=~/.emacs.d/early-init.el= and =~/.emacs.d/init.el=. If these files already
exists, they will be overwritten.

Open [[file:./my-org-outlook.org][my-org-outlook.org]] with Emacs and tangle code to initialize utilities to interface Org-mode
with Outlook using ~org-element~ and PowerShell scripts.

Open [[file:org-setup-files.org][org-setup-files.org]] with Emacs and tangle code to initialize *.setup files
in =~/.emacs.d/setup/= directory. This files are used to do basic styling when
exporting to pdf or html.

Open [[file:my-emacs-skeleton.org][my-emacs-skeleton.org]] with Emacs and tangle code to initialize an Elisp module
in the =~/.emacs.d/elisp/= directory that defines skeletons for various file templates.

* Personal settings

Personal settings can be load from =.work/settings.el= or =.home/settings.el= if
it exist in user Emacs directory.

* Notes

On windows, Emacs is looking for =init.el= in user's home directory in
=AppData\Roaming= folder. To bypass this behavior, set =HOME= environment
variable to a different path.

* Tasks list

- [1/3] Windows integration
  - [X] Create outlook appointment from org-mode SCHEDULED item
  - [ ] Create outlook email from org-mode document
  - [ ] Create an org-mode SCHEDULED item from outlook appointment (org-protocol ?)
- [ ] Macosx integration
  - [ ] Create event in calendar app from org-mode SCHEDULED item
- [1/2] Add org-mode template for project management
  - [X] Create basic project template using skeleton.el
  - [ ] Improve current skeleton
- [X] Add template for org-mode html export
- [X] Add template for org-mode pdf export
- [ ] Add template for org-mode docx export (is it possible ?)
- [ ] Add something in this README to automatically tangle all org files at once
